version: 1
external_links:
  documentation: https://adaengine.org/adaengine-docs/documentation/adaengine/
builder:
  configs:
  - platform: ios
    target: AdaEngine
  - platform: macos-xcodebuild
    scheme: AdaEngine
  - platform: macos-spm
    target: AdaEngine
  - platform: tvos
    target: AdaEngine
  - platform: visionos
    target: AdaEngine
  - documentation_targets: [AdaEngine, AdaEngineMacros, Math, AdaApp, AdaECS, AdaRender, AdaText, AdaUI, AdaInput]