load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "repos",
    srcs = ["repos.bzl"],
    visibility = ["//visibility:public"],
    deps = ["@bazel_tools//tools/build_defs/repo:git.bzl"],
)
