import AdaScriptCompilerCore
import Foundation

private enum GeneratorError: Error, CustomStringConvertible {
    case invalidArguments

    var description: String {
        switch self {
        case .invalidArguments:
            "Usage: AdaScriptGeneratorTool --output <path> --root <target-directory> --module-name <name> [script.ada ...]"
        }
    }
}

@main
struct AdaScriptGeneratorTool {
    static func main() throws {
        let arguments = Array(CommandLine.arguments.dropFirst())
        guard arguments.count >= 6,
              arguments[0] == "--output",
              arguments[2] == "--root",
              arguments[4] == "--module-name" else {
            throw GeneratorError.invalidArguments
        }

        let outputURL = URL(fileURLWithPath: arguments[1], isDirectory: false)
        let rootURL = URL(fileURLWithPath: arguments[3], isDirectory: true)
        let moduleName = arguments[5]
        let scriptURLs = arguments.dropFirst(6).map { URL(fileURLWithPath: $0, isDirectory: false) }
        let generatedSource = try makeGeneratedSource(
            moduleName: moduleName,
            scriptURLs: scriptURLs,
            rootURL: rootURL
        )

        try FileManager.default.createDirectory(
            at: outputURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        if (try? String(contentsOf: outputURL, encoding: .utf8)) != generatedSource {
            try generatedSource.write(to: outputURL, atomically: true, encoding: .utf8)
        }
    }

    private static func makeGeneratedSource(
        moduleName: String,
        scriptURLs: [URL],
        rootURL: URL
    ) throws -> String {
        let scripts = try scriptURLs.map { scriptURL in
            let source = try String(contentsOf: scriptURL, encoding: .utf8)
            return (path: relativePath(for: scriptURL, rootURL: rootURL), source: source)
        }
        let schemas = try AdaScriptSchemaParser.parse(sources: scripts.map {
            AdaScriptCompilerSource(path: $0.path, source: $0.source)
        })

        let entries = scripts
            .map { script in
                "        GravityScriptSource(path: \(swiftStringLiteral(script.path)), source: \(swiftStringLiteral(script.source)))"
            }
            .joined(separator: ",\n")
        let scriptsDeclaration = entries.isEmpty ? "[]" : "[\n\(entries)\n    ]"
        let dataDeclarations = schemas.map { schemaDeclaration($0, moduleName: moduleName) }.joined(separator: "\n\n")
        let registrations = schemas.map { schemaRegistration($0, moduleName: moduleName) }.joined(separator: "\n        ")

        return """
        // This file is generated by AdaScriptBuildPlugin. Do not edit.
        import AdaEngine

        \(dataDeclarations)

        struct AdaScriptPluginsGenerated: Plugin {
            @MainActor
            func setup(in app: borrowing AppWorlds) {
                \(registrations)
                guard !Self.sources.isEmpty else { return }
                do {
                    app.addPlugin(
                        try GravityScriptPlugin(
                            sources: Self.sources,
                            name: \(swiftStringLiteral(moduleName))
                        )
                    )
                } catch {
                    print("AdaEngine: failed to load Ada Script module \\(Self.moduleName): \\(error)")
                }
            }

            private static let moduleName = \(swiftStringLiteral(moduleName))
            private static let sources: [GravityScriptSource] = \(scriptsDeclaration)
        }

        """
    }

    private static func schemaDeclaration(_ schema: AdaScriptDataSchema, moduleName: String) -> String {
        let typeName = generatedTypeName(schema, moduleName: moduleName)
        let fields = schema.fields
            .map { field in
                "    var \(field.name): \(swiftType(field.defaultValue)) = \(swiftDefault(field.defaultValue))"
            }
            .joined(separator: "\n")
        switch schema.kind {
        case .component:
            return """
            @Component
            struct \(typeName): Codable, Sendable {
            \(fields)
            }
            """
        case .resource:
            return """
            struct \(typeName): Codable, Resource, Sendable {
            \(fields)
            }
            """
        }
    }

    private static func schemaRegistration(_ schema: AdaScriptDataSchema, moduleName: String) -> String {
        let typeName = generatedTypeName(schema, moduleName: moduleName)
        let names = "[\(swiftStringLiteral(schema.name)), \(swiftStringLiteral(schema.id))]"
        switch schema.kind {
        case .component:
            return "RuntimeTypeRegistry.registerComponent(\(typeName).self, names: \(names), makeDefault: { \(typeName)() })"
        case .resource(let autoInsert):
            let fieldDescriptors = resourceFieldDescriptors(schema, typeName: typeName)
            let registration = """
            RuntimeTypeRegistry.registerResource(\(typeName).self, names: \(names))
                    RuntimeResourceReflectionRegistry.register(\(typeName).self, fields: [
            \(fieldDescriptors)
                    ])
            """
            return autoInsert ? "\(registration)\n        app.main.insertResource(\(typeName)())" : registration
        }
    }

    private static func resourceFieldDescriptors(_ schema: AdaScriptDataSchema, typeName: String) -> String {
        schema.fields
            .map { field in
                let fieldType = swiftType(field.defaultValue)
                return """
                    unsafe EditorComponentFieldDescriptor(
                        key: \(swiftStringLiteral(field.name)),
                        label: \(swiftStringLiteral(field.name)),
                        kind: EditorComponentReflection.kind(for: \(fieldType).self),
                        isEditable: EditorComponentReflection.isEditable(\(fieldType).self),
                        accepts: { EditorComponentReflection.accepts($0, for: \(fieldType).self) },
                        read: { _ in nil },
                        write: { _, _ in nil },
                        readPointer: { pointer in
                            let resource = unsafe pointer.assumingMemoryBound(to: \(typeName).self)
                            return EditorComponentReflection.read(unsafe resource.pointee.\(field.name))
                        },
                        writePointer: { pointer, value in
                            let resource = unsafe pointer.assumingMemoryBound(to: \(typeName).self)
                            return unsafe EditorComponentReflection.write(value, to: &resource.pointee.\(field.name))
                        }
                    )
                """
            }
            .joined(separator: ",\n")
    }

    private static func generatedTypeName(_ schema: AdaScriptDataSchema, moduleName: String) -> String {
        "__AdaScript_\(swiftIdentifier(moduleName))_\(swiftIdentifier(schema.name))"
    }

    private static func swiftIdentifier(_ value: String) -> String {
        let scalars = value.unicodeScalars.map { scalar -> String in
            CharacterSet.alphanumerics.contains(scalar) || scalar == "_" ? String(scalar) : "_"
        }
        let result = scalars.joined()
        return result.first?.isNumber == true ? "_\(result)" : result
    }

    private static func swiftType(_ value: AdaScriptSchemaField.Value) -> String {
        switch value {
        case .bool: "Bool"
        case .double: "Double"
        case .int: "Int64"
        case .string: "String"
        }
    }

    private static func swiftDefault(_ value: AdaScriptSchemaField.Value) -> String {
        switch value {
        case .bool(let value): String(value)
        case .double(let value): String(value)
        case .int(let value): String(value)
        case .string(let value): swiftStringLiteral(value)
        }
    }

    private static func relativePath(for fileURL: URL, rootURL: URL) -> String {
        let filePath = fileURL.standardizedFileURL.path
        let rootPath = rootURL.standardizedFileURL.path
        let rootPrefix = rootPath.hasSuffix("/") ? rootPath : rootPath + "/"
        guard filePath.hasPrefix(rootPrefix) else {
            return fileURL.lastPathComponent
        }
        return String(filePath.dropFirst(rootPrefix.count))
    }

    private static func swiftStringLiteral(_ value: String) -> String {
        var result = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
            case 0x22:
                result += "\\\""
            case 0x5C:
                result += "\\\\"
            case 0x0A:
                result += "\\n"
            case 0x0D:
                result += "\\r"
            case 0x09:
                result += "\\t"
            case 0x20...0x7E:
                result.unicodeScalars.append(scalar)
            default:
                result += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
            }
        }
        result += "\""
        return result
    }
}
