import Foundation

private enum GeneratorError: Error, CustomStringConvertible {
    case invalidArguments

    var description: String {
        switch self {
        case .invalidArguments:
            "Usage: AdaScriptGeneratorTool --output <path> --root <target-directory> --module-name <name> [script.ada ...]"
        }
    }
}

@main
struct AdaScriptGeneratorTool {
    static func main() throws {
        let arguments = Array(CommandLine.arguments.dropFirst())
        guard arguments.count >= 6,
              arguments[0] == "--output",
              arguments[2] == "--root",
              arguments[4] == "--module-name" else {
            throw GeneratorError.invalidArguments
        }

        let outputURL = URL(fileURLWithPath: arguments[1], isDirectory: false)
        let rootURL = URL(fileURLWithPath: arguments[3], isDirectory: true)
        let moduleName = arguments[5]
        let scriptURLs = arguments.dropFirst(6).map { URL(fileURLWithPath: $0, isDirectory: false) }
        let generatedSource = try makeGeneratedSource(
            moduleName: moduleName,
            scriptURLs: scriptURLs,
            rootURL: rootURL
        )

        try FileManager.default.createDirectory(
            at: outputURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        if (try? String(contentsOf: outputURL, encoding: .utf8)) != generatedSource {
            try generatedSource.write(to: outputURL, atomically: true, encoding: .utf8)
        }
    }

    private static func makeGeneratedSource(
        moduleName: String,
        scriptURLs: [URL],
        rootURL: URL
    ) throws -> String {
        let scripts = try scriptURLs.map { scriptURL in
            let source = try String(contentsOf: scriptURL, encoding: .utf8)
            return (path: relativePath(for: scriptURL, rootURL: rootURL), source: source)
        }

        let entries = scripts
            .map { script in
                "        GravityScriptSource(path: \(swiftStringLiteral(script.path)), source: \(swiftStringLiteral(script.source)))"
            }
            .joined(separator: ",\n")
        let scriptsDeclaration = entries.isEmpty ? "[]" : "[\n\(entries)\n    ]"

        return """
        // This file is generated by AdaScriptBuildPlugin. Do not edit.
        import AdaEngine

        struct AdaScriptPluginsGenerated: Plugin {
            @MainActor
            func setup(in app: borrowing AppWorlds) {
                guard !Self.sources.isEmpty else { return }
                do {
                    app.addPlugin(
                        try GravityScriptPlugin(
                            sources: Self.sources,
                            name: \(swiftStringLiteral(moduleName))
                        )
                    )
                } catch {
                    print("AdaEngine: failed to load Ada Script module \\(Self.moduleName): \\(error)")
                }
            }

            private static let moduleName = \(swiftStringLiteral(moduleName))
            private static let sources: [GravityScriptSource] = \(scriptsDeclaration)
        }

        """
    }

    private static func relativePath(for fileURL: URL, rootURL: URL) -> String {
        let filePath = fileURL.standardizedFileURL.path
        let rootPath = rootURL.standardizedFileURL.path
        let rootPrefix = rootPath.hasSuffix("/") ? rootPath : rootPath + "/"
        guard filePath.hasPrefix(rootPrefix) else {
            return fileURL.lastPathComponent
        }
        return String(filePath.dropFirst(rootPrefix.count))
    }

    private static func swiftStringLiteral(_ value: String) -> String {
        var result = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
            case 0x22:
                result += "\\\""
            case 0x5C:
                result += "\\\\"
            case 0x0A:
                result += "\\n"
            case 0x0D:
                result += "\\r"
            case 0x09:
                result += "\\t"
            case 0x20...0x7E:
                result.unicodeScalars.append(scalar)
            default:
                result += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
            }
        }
        result += "\""
        return result
    }
}
